// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbjitjfgcpagmttrwfao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhiaml0amZnY3BhZ210dHJ3ZmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mzk5NjQsImV4cCI6MjA2MDQxNTk2NH0.C-tUhrZEQ7DAhMTMMF1ILC5JJuWHLa5zD2-x9uXVy0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);